config/routes.rb
Scisco::Application.routes.draw do
  resources :questions do
    put :upvote, on: :member
  end

  root to: 'questions#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :notes, :title

  validates_presence_of :title
  
  scope :unanswered, -> { where(answered: false) }
  scope :answered, -> { where(answered: true) }

  def self.search(term)
    return scoped unless term

    term.downcase!
    where('LOWER(title) LIKE ? OR LOWER(notes) LIKE ?', "%#{term}%", "%#{term}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def upvote
    @q = Question.find_by_id(params[:id])
    @q.increment!(:votes) unless @q.votes > 999

    respond_to do |format|
      format.js
    end
  end

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.search(params[:search])
    if params[:sort].to_s.downcase == 'popular'
      @questions = @questions.order('votes desc')
    else
      @questions = @questions.order('updated_at desc')
    end
    if params[:answered].blank?
      @questions = @questions.unanswered
    end
    
    @questions = @questions.page(params[:page]).per(25)

    @question = Question.new
    @show_form = false

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to root_url, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html do
          @questions = Question.page(params[:page]).per(20)
          @show_form = true
          render "index"
        end

        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])
    if params[:answered].present?
      @question.answered = params[:answered] == 'true'
    end
    
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scisco" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/"><i class="icon-flag"></i> Scisco</a>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy;2013 The Starter League</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <fieldset>
    <legend>Ask a Question</legend>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'span7', placeholder: 'Required: Enter a brief title here.' %>
    <br/>
    <%= f.label :notes %>
      <span><em>Optional: Provide more context or the full form of your question below.</em>
      </span>
    <%= f.text_area :notes, class: 'span7', rows: 4 %>
  </fieldset>
    <%= f.submit "Submit This Question", class: 'btn btn-success btn-large', id: 'question_submit' %> or <%= link_to "Cancel", root_url, id: 'question_cancel_link', class: 'btn btn-danger' %>

<% end %>

app/views/questions/_question.html.erb
<tr id="<%= dom_id(question) %>">
  <td>
    <span id="question_<%= question.id %>_votes"><%= question.votes %></span>
    <%= link_to upvote_question_path(question), remote: true, method: 'put', class: 'btn' do %>
        <i class="icon-thumbs-up"></i>
    <% end %>
    <% if question.answered? %>
      <%= link_to "Reopen", question_url(question, :answered => false), :method => :put, remote: true, :class => 'question_action' %>
    <% else %>
      <%= link_to "Mark as Answered", question_url(question, :answered => true), :method => :put, remote: true, :class => 'question_action' %>
    <% end %>
  </td>
  
  <td width="75%">
    <%= link_to question.title, question, title: question.notes, data: { question_id: question.id }, class: 'question_details' %>
    <span class="question_date pull-right">
      <%= question.updated_at.strftime("%a, %b %e") %> #<%= question.id %>
    </span>
    
    <%= form_for question, remote: true do |q| %>
      <br/>
      <fieldset>
        <%= q.label :notes, "You can provide brief details or a code snippet here:" %><%= q.text_area :notes, :rows => 4, class: 'span6' %>
      </fieldset>
      <%= q.submit "Save", class: 'btn btn-success' %> or <%= link_to "Cancel", root_url, class: 'question_details', data: { question_id: question.id } %>
    <% end %>
  </td>
</tr>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="row">
  <div class="pull-right">
    <%= form_tag root_url, method: 'get', id: 'search_form' do %>
      <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: "Search..." %>
      <%= link_to "Clear", root_url %>
    <% end %>
  </div>
  <div class="span8">
    <%= link_to "I Have a Question!", new_question_path, id: 'new_question_link', class: 'btn btn-success btn-large' %>
    <%= render 'form' %>
  </div>
</div>
<br/>
<br/>

<div class="row">
  <div class="span4">
    <label>
    Sort by: 
    <%= link_to "Most Recent", questions_url %> |
    <%= link_to "Most Popular", questions_url(sort: :popular) %> 
    </label>
  </div>
  <div class="span4">
    <%= form_tag questions_url, method: 'get', id: 'toggle_form' do %>
      <label class="checkbox">
        <%= check_box_tag :answered, "1", params[:answered].present? %>Show answered questions
      </label>
    <% end %>
  </div>
</div>
<div class="row">
  <table class="table span12 questions">
    <thead>
      <tr>
        <th>Votes</th>
        <th>Question</th>
      </tr>
    <tbody>
      <%= render @questions %>
    </tbody>
  </table>
</div>
<div class="row">
  <div class="pull-right"><%= paginate @questions %></div>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @question.title %>
</p>

<p>
  <b>Notes:</b>
  <%= @question.notes %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/update.js.erb
$("#edit_question_<%= @question.id %>").hide();
// $("#<%= dom_id(@question) %> .question_details").attr("title", "<%= j(@question.notes) %>");
$("#<%= dom_id(@question) %>").replaceWith("<%= j(render('question', question: @question)) %>")

app/views/questions/upvote.js.erb
$("#question_<%= @q.id %>_votes").html("<%= @q.votes %>");
$("#<%= dom_id(@q) %>").effect("highlight", {}, "slow");